const tabNames = {
  VERTEX_SHADER: 'VERTEX_SHADER',
  FRAGMENT_SHADER: 'FRAGMENT_SHADER',
  ADD_NEW_SHADER: 'ADD_NEW_SHADER',
  SHADERS_GALLERY: 'SHADERS_GALLERY',
  SHADERS_SETTINGS: 'SHADERS_SETTINGS',
  UPLOAD_SHADER: 'UPLOAD_SHADER',
};

export default tabNames;
