const actionTypes = {
  MATERIAL_EDITOR_ON_SET_CTRL_BOX_WIDTH: 'MATERIAL_EDITOR_ON_SET_CTRL_BOX_WIDTH',
  SHADER_EDITOR_ON_SET_CTRL_BOX_WIDTH: 'SHADER_EDITOR_ON_SET_CTRL_BOX_WIDTH',
  GET_MATERIAL_EDITOR_ITEM_OBJ_LIST: 'GET_MATERIAL_EDITOR_ITEM_OBJ_LIST',
  ON_REMOVE_ITEM_OBJ_BY_ID: 'ON_REMOVE_ITEM_OBJ_BY_ID',
  ON_LOAD_ITEM_OBJ_LIST: 'ON_LOAD_ITEM_OBJ_LIST',
};

export default actionTypes;
