const actionTypes = {
  GET_MATERIAL_EDITOR_ITEM_OBJ_LIST: 'GET_MATERIAL_EDITOR_ITEM_OBJ_LIST',
  ON_REMOVE_ITEM_OBJ_BY_ID: 'ON_REMOVE_ITEM_OBJ_BY_ID',
  ON_LOAD_ITEM_OBJ_LIST: 'ON_LOAD_ITEM_OBJ_LIST',
};

export default actionTypes;
