const mutationTypes = {
  // common
  REMOVE_GEOMETRIC_OBJECT_BY_ID: 'REMOVE_GEOMETRIC_OBJECT_BY_ID',
  LOAD_GEOMETRIC_OBJECTS_SUCCESS: 'LOAD_GEOMETRIC_OBJECTS_SUCCESS',
  LOAD_GLSL_PROGRAMS_SUCCESS: 'LOAD_GLSL_PROGRAMS_SUCCESS',

  // material editor
  MATERIAL_EDITOR_TOGGLE_FULLSCREEN_MODE: 'MATERIAL_EDITOR_TOGGLE_FULLSCREEN_MODE',
  MATERIAL_EDITOR_SET_ACTIVE_MATERIAL_TYPE: 'MATERIAL_EDITOR_SET_ACTIVE_MATERIAL_TYPE',
  MATERIAL_EDITOR_TOGGLE_OBJECTS_LIST: 'MATERIAL_EDITOR_TOGGLE_OBJECTS_LIST',
  MATERIAL_EDITOR_SET_PANEL_CONTROLS_WIDTH: 'MATERIAL_EDITOR_SET_PANEL_CONTROLS_WIDTH',

  // shader editor
  SHADER_EDITOR_TOGGLE_FULLSCREEN_MODE: 'SHADER_EDITOR_TOGGLE_FULLSCREEN_MODE',
  SHADER_EDITOR_SET_ACTIVE_SHADER_TYPE: 'SHADER_EDITOR_SET_ACTIVE_SHADER_TYPE',
  SHADER_EDITOR_SET_ACTIVE_CONTROLS_TYPE: 'SHADER_EDITOR_SET_ACTIVE_CONTROLS_TYPE',
  SHADER_EDITOR_TOGGLE_FOOTER_CONTROLS: 'SHADER_EDITOR_TOGGLE_FOOTER_CONTROLS',
  SHADER_EDITOR_TOGGLE_OBJECTS_LIST: 'SHADER_EDITOR_TOGGLE_OBJECTS_LIST',
  SHADER_EDITOR_SET_SHADER_VALUE_BY_TYPE: 'SHADER_EDITOR_SET_SHADER_VALUE_BY_TYPE',
  SHADER_EDITOR_SET_PANEL_CONTROLS_WIDTH: 'SHADER_EDITOR_SET_PANEL_CONTROLS_WIDTH',
  SHADER_EDITOR_SET_FOOTER_CONTROLS_HEIGHT: 'SHADER_EDITOR_SET_FOOTER_CONTROLS_HEIGHT'
};

export default mutationTypes;
