const mutationTypes = {
  // playground
  SET_OBJECT_PROPERTY_VALUE: 'SET_OBJECT_PROPERTY_VALUE',
  SET_GEOMETRY_PROPERTY_VALUE: 'SET_GEOMETRY_PROPERTY_VALUE',
  SET_MATERIAL_PROPERTY_VALUE: 'SET_MATERIAL_PROPERTY_VALUE',
  SET_ACTIVE_EDITOR_NAME: 'SET_ACTIVE_EDITOR_NAME',
  SET_EDITABLE_OBJECT_IDS: 'SET_EDITABLE_OBJECT_IDS',
  TOGGLE_MESHES_LIST: 'TOGGLE_MESHES_LIST',
  TOGGLE_OPEN_GALLERY: 'TOGGLE_OPEN_GALLERY',
  SET_TRANSFORMATION_MODE: 'SET_TRANSFORMATION_MODE',

  TOGGLE_CREATE_NEW_CONTROL_AREA: 'TOGGLE_CREATE_NEW_CONTROL_AREA',
  CREATE_CONTROL: 'CREATE_CONTROL',
  CANCEL_CREATE_CONTROL: 'CANCEL_CREATE_CONTROL',
  REMOVE_CONTROL: 'REMOVE_CONTROL',
  SAVE_SHADER: 'SAVE_SHADER',
  SET_CONTROL_VALUE: 'SET_CONTROL_VALUE',
  SET_EDIT_CONTROL: 'SET_EDIT_CONTROL',

  // lighting editor
  SET_PANEL_CONTROLS_WIDTH_OF_LIGHTING_EDITOR: 'SET_PANEL_CONTROLS_WIDTH_OF_LIGHTING_EDITOR',

  // particles editor
  SET_PANEL_CONTROLS_WIDTH_OF_PARTICLES_EDITOR: 'SET_PANEL_CONTROLS_WIDTH_OF_PARTICLES_EDITOR',

  // material editor
  LOAD_MATERIALS_SUCCESS: 'LOAD_MATERIALS_SUCCESS',
  SET_SELECTED_MATERIAL: 'SET_SELECTED_MATERIAL',
  SET_ACTIVE_MATERIAL_TYPE_ID: 'SET_ACTIVE_MATERIAL_TYPE_ID',
  SET_PANEL_CONTROLS_WIDTH_OF_OGM_EDITOR: 'SET_PANEL_CONTROLS_WIDTH_OF_OGM_EDITOR',

  // shader editor
  SET_ACTIVE_SHADER_TYPE: 'SET_ACTIVE_SHADER_TYPE',
  SET_ACTIVE_CONTROL_TYPE: 'SET_ACTIVE_CONTROL_TYPE',
  TOGGLE_FOOTER_CONTROLS: 'TOGGLE_FOOTER_CONTROLS',
  SET_SHADER_VALUE_BY_TYPE: 'SET_SHADER_VALUE_BY_TYPE',
  SET_FOOTER_CONTROLS_HEIGHT: 'SET_FOOTER_CONTROLS_HEIGHT',
  SET_PANEL_CONTROLS_WIDTH_OF_SHADER_EDITOR: 'SET_PANEL_CONTROLS_WIDTH_OF_SHADER_EDITOR'
};

export default mutationTypes;
